{
  imports = [
    ./allow-unfree.nix
    ./apparmor.nix
    ./audit.nix
    ./auto-cpufreq.nix
    ./auto-upgrade.nix
    ./bootloader.nix
    ./clamav.nix
    ../docker/docker.nix
    ./experimental-features.nix
    ./fail2ban.nix
    ./firewall.nix
    ./firmware.nix
    ./hostname.nix
    ./kernel.nix
    ./network-manager.nix
    ./noexec.nix
    ./optimise.nix
    ./ssh.nix
    ./state-version.nix
    ./syncthing.nix
    ./tailscale.nix
    ./timezone-locales.nix
    ./users.nix
  ];
}
