{
  imports = [
    ./hardware-configuration.nix
    ../../modules/atd.nix
    ../../modules/bluetooth.nix
    ../../modules/common
    ../../modules/firefox.nix
    ../../modules/cups.nix
    ../../modules/intel.nix
    ../../modules/kde-plasma.nix
    ../../modules/laptop.nix
    ../../modules/ld.nix
    ../../modules/pipewire.nix
    ../../modules/pkgs.nix
    ../../modules/samba.nix
    ../../modules/swap.nix
    ../../modules/touchpad.nix
    ../../modules/vms.nix
  ];
}
