{
  imports = [
    ./hardware-configuration.nix
    ../../modules/apparmor.nix
    ../../modules/atd.nix
    ../../modules/bluetooth.nix
    ../../modules/clamav.nix
    ../../modules/common
    ../../modules/cups.nix
    ../../modules/docker/docker.nix
    ../../modules/fail2ban.nix
    ../../modules/fish.nix
    ../../modules/intel.nix
    ../../modules/kde-plasma.nix
    ../../modules/laptop.nix
    ../../modules/ld.nix
    ../../modules/pipewire.nix
    ../../modules/pkgs-gaming.nix
    ../../modules/pkgs.nix
    ../../modules/sops.nix
    ../../modules/syncthing.nix
    ../../modules/touchpad.nix
    ../../modules/virtualbox.nix
    ../../modules/vscodiym.nix
  ];
}
