# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."wg-easy" = {
    image = "ghcr.io/wg-easy/wg-easy";
    environment = {
      "LANG" = "en";
      "PASSWORD_HASH" = "$2a$12$.HhA/iYXJCEhKyrI2KQBteFcr53AVEvPg2KJ6tr4mjXzDwSHkAjgG";
    };
    environmentFiles = [ config.sops.secrets."wg-easy.env".path ];
    volumes = [
      "/home/maxlttr/docker/wg-easy/etc_wireguard:/etc/wireguard:rw"
    ];
    ports = [
      "51820:51820/udp"
      "51821:51821/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--cap-add=SYS_MODULE"
      "--network-alias=wg-easy"
      "--network=wg-easy_default"
      "--sysctl=net.ipv4.conf.all.src_valid_mark=1"
      "--sysctl=net.ipv4.ip_forward=1"
    ];
  };
  systemd.services."docker-wg-easy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wg-easy_default.service"
    ];
    requires = [
      "docker-network-wg-easy_default.service"
    ];
    partOf = [
      "docker-compose-wg-easy-root.target"
    ];
    wantedBy = [
      "docker-compose-wg-easy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wg-easy_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wg-easy_default";
    };
    script = ''
      docker network inspect wg-easy_default || docker network create wg-easy_default
    '';
    partOf = [ "docker-compose-wg-easy-root.target" ];
    wantedBy = [ "docker-compose-wg-easy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wg-easy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
