# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."it-tools-it-tools" = {
    image = "ghcr.io/corentinth/it-tools:latest";
    ports = [
      "8888:80/tcp"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.it-tools-https.entrypoints" = "websecure";
      "traefik.http.routers.it-tools-https.rule" = "Host(`it-tools.maxlttr7.duckdns.org`)";
      "traefik.http.routers.it-tools-https.tls" = "true";
      "traefik.http.routers.it-tools-https.tls.certresolver" = "myresolver";
      "traefik.http.services.it-tools-https.loadbalancer.server.port" = "8888";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=it-tools"
      "--network=proxy"
    ];
  };
  systemd.services."docker-it-tools-it-tools" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-it-tools-root.target"
    ];
    wantedBy = [
      "docker-compose-it-tools-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-it-tools-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
