name: it-tools

services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools-https.tls=true
      - traefik.http.routers.it-tools-https.tls.certresolver=myresolver
      - traefik.http.routers.it-tools-https.entrypoints=websecure
      - traefik.http.routers.it-tools-https.rule=Host(`it-tools.maxlttr7.duckdns.org`)
      - traefik.http.services.it-tools-https.loadbalancer.server.port=8888
    ports:
      - "8888:80"
    restart: unless-stopped

networks:
  proxy:
    external: true