services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - PUID=1001
      - PGID=100
      - GENERIC_TIMEZONE="Europe/Paris"
      - TZ="Europe/Paris"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - ~/Syncthing/docker/n8n:/home/node/.n8n
    ports:
      - 5678:5678
    restart: unless-stopped
