services:
  traefik:
    image: traefik:latest
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./traefik-config.yml:/etc/traefik/traefik.yml
      - ~/docker/traefik/:/var/traefik/certs/:rw
      # touch ~/docker/traefik/acme.json && chmod 600 ~/docker/traefik/acme.json
    command:
      - "--global.sendAnonymousUsage=false"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.myresolver.acme.email=maxime.lettier@protonmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/var/traefik/certs/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    restart: unless-stopped

networks:
  proxy:
    external: true