# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."n8n" = {
    image = "docker.n8n.io/n8nio/n8n";
    environment = {
      "GENERIC_TIMEZONE" = "\"Europe/Paris\"";
      "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS" = "true";
      "N8N_RUNNERS_ENABLED" = "true";
      "TZ" = "\"Europe/Paris\"";
    };
    volumes = [
      "/home/maxlttr/Syncthing/docker/n8n:/home/node/.n8n:rw"
    ];
    ports = [
      "5678:5678/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=n8n"
      "--network=n8n_default"
    ];
  };
  systemd.services."podman-n8n" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-n8n_default.service"
    ];
    requires = [
      "podman-network-n8n_default.service"
    ];
    partOf = [
      "podman-compose-n8n-root.target"
    ];
    wantedBy = [
      "podman-compose-n8n-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-n8n_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f n8n_default";
    };
    script = ''
      podman network inspect n8n_default || podman network create n8n_default
    '';
    partOf = [ "podman-compose-n8n-root.target" ];
    wantedBy = [ "podman-compose-n8n-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-n8n-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
