# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."headscale" = {
    image = "headscale/headscale";
    volumes = [
      "/home/maxlttr/Syncthing/docker/.config/headscale:/etc/headscale:rw"
    ];
    ports = [
      "0.0.0.0:8080:8080/tcp"
      "0.0.0.0:9090:9090/tcp"
    ];
    cmd = [ "serve" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=headscale"
      "--network=headscale_default"
    ];
  };
  systemd.services."docker-headscale" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-headscale_default.service"
    ];
    requires = [
      "docker-network-headscale_default.service"
    ];
    partOf = [
      "docker-compose-headscale-root.target"
    ];
    wantedBy = [
      "docker-compose-headscale-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-headscale_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f headscale_default";
    };
    script = ''
      docker network inspect headscale_default || docker network create headscale_default
    '';
    partOf = [ "docker-compose-headscale-root.target" ];
    wantedBy = [ "docker-compose-headscale-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-headscale-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
