# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."portainer" = {
    image = "portainer/portainer-ce:2.21.5";
    environment = {
      "PGID" = "100";
      "PUID" = "1001";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/home/maxlttr/Syncthing/docker/.config/portainer/portainer_data:/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "127.0.0.1:8000:8000/tcp"
      "127.0.0.1:9443:9443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=portainer"
      "--network=nginx_reverse_proxy_nginx"
    ];
  };
  systemd.services."docker-portainer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-portainer-root.target"
    ];
    wantedBy = [
      "docker-compose-portainer-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-portainer-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
