services:
  suaps:
    image: ghcr.io/flash2974/reservercreneausuaps-app:latest
    networks:
      - proxy
    volumes:
      - ./config/config.json:/app/config/config.json
    env_file:
      - ~/docker/suaps.env
    ports:
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.https.tls.certresolver=myresolver
      - traefik.http.routers.https.tls=true
      - traefik.http.routers.https.entrypoints=websecure
      - traefik.http.routers.https.rule=Host(`suaps.maxlttr7.duckdns.org`)
      - traefik.http.services.https.loadbalancer.server.port=5000
    restart: unless-stopped

networks:
  proxy:
    external: true
