name: traefik

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    networks:
      - proxy
    command: 
      --configFile=traefik-config.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

networks:
  proxy:
    driver: bridge