# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."traefik" = {
    image = "traefik:latest";
    volumes = [
      "/home/maxlttr/Syncthing/docker/.config/traefik/acme.json:/acme.json:rw"
      "/home/maxlttr/nix-config/modules/docker/traefik-config.yml:/etc/traefik/traefik.yml:ro"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "80:80/tcp"
      "443:443/tcp"
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=reverse-proxy"
      "--network=traefik_proxy"
    ];
  };
  systemd.services."docker-traefik" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-traefik_proxy.service"
    ];
    requires = [
      "docker-network-traefik_proxy.service"
    ];
    partOf = [
      "docker-compose-traefik-root.target"
    ];
    wantedBy = [
      "docker-compose-traefik-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-traefik_proxy" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f traefik_proxy";
    };
    script = ''
      docker network inspect traefik_proxy || docker network create traefik_proxy --driver=bridge
    '';
    partOf = [ "docker-compose-traefik-root.target" ];
    wantedBy = [ "docker-compose-traefik-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-traefik-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
