name: traefik

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    networks:
      - proxy
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ~/Syncthing/docker/.config/traefik/acme.json:/acme.json
    restart: unless-stopped

networks:
  proxy:
    driver: bridge