# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."uptime-kuma" = {
    image = "louislam/uptime-kuma:1";
    volumes = [
      "/home/maxlttr/Syncthing/docker/.config/uptime-kuma/uptime-kuma:/app/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "127.0.0.1:3001:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=portainer"
      "--network=nginx_reverse_proxy_nginx"
    ];
  };
  systemd.services."docker-uptime-kuma" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-uptime-kuma-root.target"
    ];
    wantedBy = [
      "docker-compose-uptime-kuma-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-uptime-kuma-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
