# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."deluge" = {
    image = "lscr.io/linuxserver/deluge:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/home/maxlttr/.config/deluge/config:/config:rw"
      "/home/maxlttr/Syncthing/movies:/downloads:rw"
    ];
    dependsOn = [
      "vpn_stack-gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:vpn_stack-gluetun"
    ];
  };
  systemd.services."docker-deluge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-vpn_stack-root.target"
    ];
    wantedBy = [
      "docker-compose-vpn_stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vpn_stack-gluetun" = {
    image = "qmcgaw/gluetun";
    environment = {
      "VPN_SERVICE_PROVIDER" = "custom";
      "VPN_TYPE" = "wireguard";
      "WIREGUARD_ADDRESSES" = "10.8.0.2/24";
      "WIREGUARD_ENDPOINT_IP" = "107.175.69.20";
      "WIREGUARD_ENDPOINT_PORT" = "51820";
      "WIREGUARD_PRESHARED_KEY" = "S/e70Ee+Ihk+fWlbgojwmoyDhNRTTFKMeWeDsVN4JEo=";
      "WIREGUARD_PRIVATE_KEY" = "EKViEOODpYFcsSTFa5gxhU19uwK6tMuzEgdqT4kUnU4=";
      "WIREGUARD_PUBLIC_KEY" = "XWmrz9lUWW423HVnY0qKwErZcTEgs0gRifTrsX85LG4=";
    };
    ports = [
      "8112:8112/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=gluetun"
      "--network=vpn_stack_default"
    ];
  };
  systemd.services."docker-vpn_stack-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-vpn_stack_default.service"
    ];
    requires = [
      "docker-network-vpn_stack_default.service"
    ];
    partOf = [
      "docker-compose-vpn_stack-root.target"
    ];
    wantedBy = [
      "docker-compose-vpn_stack-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-vpn_stack_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vpn_stack_default";
    };
    script = ''
      docker network inspect vpn_stack_default || docker network create vpn_stack_default
    '';
    partOf = [ "docker-compose-vpn_stack-root.target" ];
    wantedBy = [ "docker-compose-vpn_stack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vpn_stack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
