name: portainer

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/Syncthing/docker/.config/portainer/portainer_data:/data
    ports:
      - "9443:9443"
    restart: unless-stopped
