{
  imports = [
    ./common

    ./atd.nix
    ./auditd.nix
    ./autoAmpDL.nix
    ./autoCpufreq.nix
    ./autoFlakeUpdate.nix
    ./bluetooth.nix
    ./borgbackup.nix
    ./cups.nix
    ./eduvpn.nix
    ./fail2ban.nix
    ./fan.nix
    ./flatpak.nix
    ./gaming.nix
    ./gnupg.nix
    ./hyprland.nix
    ./impermanence.nix
    ./intel.nix
    ./kdePlasma.nix
    ./ld.nix
    ./nvidia.nix
    ./pipewire.nix
    ./powertopAutotune.nix
    ./samba.nix
    ./ssh.nix
    ./swap.nix
    ./tlp.nix
    ./touchpad.nix
    ./virtualbox.nix
    ./vms.nix
  ];
}
