{ lib, config, pkgs, settings, ... }:

{
  options = {
    custom.fan.enable = lib.mkEnableOption "Enbale fans control";
  };

  config = lib.mkIf config.custom.fan.enable {
    boot.kernelModules = [ "nct6775" ];

    hardware.fancontrol = {
      enable = true;
      config = ''
        # Configuration file generated by pwmconfig, changes will be lost
        INTERVAL=10
        DEVPATH=hwmon1=devices/platform/coretemp.0 hwmon2=devices/platform/nct6775.2592
        DEVNAME=hwmon1=coretemp hwmon2=nct6779
        FCTEMPS=hwmon2/pwm2=hwmon1/temp1_input
        FCFANS= hwmon2/pwm2=hwmon2/fan2_input
        MINTEMP=hwmon2/pwm2=30
        MAXTEMP=hwmon2/pwm2=70
        MINSTART=hwmon2/pwm2=150
        MINSTOP=hwmon2/pwm2=100
      '';
    };

    environment.systemPackages = with pkgs.stable; [
      gnuplot
      lm_sensors
    ];
  };
}
