services:
  gluetun-deluge:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    env_file:
      - ${HOME}/.config/sops-nix/secrets/vpn.env
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    depends_on:
      - gluetun-deluge
    network_mode: "service:gluetun-deluge"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/docker/deluge/config:/config
      - ${HOME}/docker/movies:/downloads
    restart: unless-stopped
