services:
  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${HOME}/docker/homeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    #   - /run/dbus:/run/dbus:ro # For bluetooth support
    privileged: true
    network_mode: host # UI accessible via port 8123
    environment:
      TZ: Europe/Paris
    # devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
