services:
  i2p:
    image: geti2p/i2p:latest
    environment:
      - JVM_XMX=512m
      - EXT_PORT=54323
    volumes:
      - ${HOME}/docker/i2p/i2pconfig:/i2p/.i2p
      - ${HOME}/docker/i2p/i2ptorrents:/i2psnark
    ports:
      - "0.0.0.0:4444:4444"   # HTTP Proxy
      # - "127.0.0.1:4445:4445"   # HTTPS Proxy
      # - "127.0.0.1:6668:6668"   # IRC Proxy
      # - "127.0.0.1:7654:7654"   # I2CP Protocol
      # - "127.0.0.1:7656:7656"   # SAM Bridge
      - "0.0.0.0:7657:7657"   # Router Console
      # - "127.0.0.1:7658:7658"   # I2P Site (eepsite)
      # - "127.0.0.1:7659:7659"   # SMTP Proxy
      # - "127.0.0.1:7660:7660"   # POP3 Proxy
      - "54323:12345"           # I2NP TCP
      - "54323:12345/udp"       # I2NP UDP
    restart: unless-stopped