services:
  rustdesk-hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - $STATE_DIRECTORY/rustdesk/hbbs:/root
    network_mode: "host"

    depends_on:
      - rustdesk-hbbr
    restart: unless-stopped

  rustdesk-hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - $STATE_DIRECTORY/rustdesk/hbbr:/root
    network_mode: "host"
    restart: unless-stopped
