services:
  suaps:
    image: ghcr.io/flash2974/reservercreneausuaps-app:latest
    volumes:
      - ${HOME}/docker/suaps/config.json:/app/config/config.json
    env_file:
      - ${HOME}/.config/sops-nix/secrets/suaps.env
    ports:
      - 127.0.0.1:5000:5000
      - "${TAILSCALE_IP}:5000:5000"
    restart: unless-stopped
