services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - ${HOME}/docker/uptime-kuma/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:3001:3001
      - "${TAILSCALE_IP}:3001:3001"
    restart: unless-stopped
