name: nextcloud

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    networks: 
      - nginx_reverse_proxy_nginx
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ~/Syncthing/docker/.config/nextcloud/config:/config
      - ~/Syncthing/nextcloud:/data
    ports:
      - "127.0.0.1:8888:443"
    restart: unless-stopped

networks:
  nginx_reverse_proxy_nginx:
    external: true
