# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."deluge" = {
    image = "lscr.io/linuxserver/deluge:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1001";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/home/maxlttr/docker/deluge/config:/config:rw"
      "/home/maxlttr/docker/movies:/downloads:rw"
    ];
    dependsOn = [
      "gluetun-deluge"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun-deluge"
    ];
  };
  systemd.services."docker-deluge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-deluge-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-deluge-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."gluetun-deluge" = {
    image = "qmcgaw/gluetun";
    environment = {
      "VPN_SERVICE_PROVIDER" = "custom";
      "VPN_TYPE" = "wireguard";
      "WIREGUARD_ADDRESSES" = "!!!!!!!!!!!!!!!!!";
      "WIREGUARD_ENDPOINT_IP" = "!!!!!!!!!!!!!!!!!";
      "WIREGUARD_ENDPOINT_PORT" = "!!!!!!!!!!!!!!!!!";
      "WIREGUARD_PRESHARED_KEY" = "!!!!!!!!!!!!!!!!!";
      "WIREGUARD_PRIVATE_KEY" = "!!!!!!!!!!!!!!!!!";
      "WIREGUARD_PUBLIC_KEY" = "!!!!!!!!!!!!!!!!!";
    };
    ports = [
      "8112:8112/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=gluetun-deluge"
      "--network=deluge-stack_default"
    ];
  };
  systemd.services."docker-gluetun-deluge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-deluge-stack_default.service"
    ];
    requires = [
      "docker-network-deluge-stack_default.service"
    ];
    partOf = [
      "docker-compose-deluge-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-deluge-stack-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-deluge-stack_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f deluge-stack_default";
    };
    script = ''
      docker network inspect deluge-stack_default || docker network create deluge-stack_default
    '';
    partOf = [ "docker-compose-deluge-stack-root.target" ];
    wantedBy = [ "docker-compose-deluge-stack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-deluge-stack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
