# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1001";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/home/maxlttr/docker/jellyfin/library:/config:rw"
      "/home/maxlttr/docker/movies:/data/movies:rw"
      "/home/maxlttr/docker/tvshows:/data/tvshows:rw"
    ];
    ports = [
      "8096:8096/tcp"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.jellyfin-https.entrypoints" = "websecure";
      "traefik.http.routers.jellyfin-https.rule" = "Host(`jellyfin.maxlttr7.duckdns.org`)";
      "traefik.http.routers.jellyfin-https.tls" = "true";
      "traefik.http.routers.jellyfin-https.tls.certresolver" = "myresolver";
      "traefik.http.services.jellyfin-https.loadbalancer.server.port" = "8096";
    };
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--network-alias=jellyfin"
      "--network=proxy"
    ];
  };
  systemd.services."docker-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "docker-compose-jellyfin-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
