name: jellyfin

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin-http.rule=Host(`jellyfin.maxlttr7.duckdns.org`)
      - traefik.http.routers.jellyfin-http.entrypoints=web
      - traefik.http.services.jellyfin-http.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin-https.tls=true
      - traefik.http.routers.jellyfin-https.tls.certresolver=myresolver
      - traefik.http.routers.jellyfin-https.entrypoints=websecure
      - traefik.http.routers.jellyfin-https.rule=Host(`jellyfin.maxlttr7.duckdns.org`)
      - traefik.http.services.jellyfin-https.loadbalancer.server.port=8096
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ~/Syncthing/docker/.config/jellyfin/library:/config
      - ~/Syncthing/movies:/data/movies
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true