name: traefik

services:
  traefik:
    image: traefik:latest
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-config.yml:/etc/traefik/traefik.yml
      - ~/docker/traefik/:/var/traefik/certs/:rw
      # touch ~/docker/traefik/acme.json && chmod 600 ~/docker/traefik/acme.json
    restart: unless-stopped

networks:
  proxy:
    external: true