name: traefik

services:
  ttraefik:
    image: traefik:latest
    container_name: traefik
    command: --configFile=/etc/traefik/traefik.yml
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-config.yml:/etc/traefik/traefik.yml:ro
      - ~/Syncthing/docker/.config/traefik/:/var/traefik/certs/:rw
    restart: unless-stopped

networks:
  proxy:
    driver: bridge