name: traefik

services:
  traefik:
    image: traefik:latest
    #container_name: traefik
    deploy:
      mode: replicated
      replicas: 3
    #command: --configFile=/etc/traefik/traefik-config.yml
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-config.yml:/etc/traefik/traefik.yml
      - ~/docker/traefik/:/var/traefik/certs/:rw
    restart: always

networks:
  proxy:
    driver: bridge