name: git-leaks

on:
  pull_request:
  push:
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Notifications
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ GitLeaks scan completed\"}"